apiVersion: v1
kind: Service
metadata:
  labels:
  
    run: smokey-server
  name: smokey-service
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    run: smokey-server
