apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: smokey-server
  name: smokey-server
spec:
  replicas: 3
  selector:
    matchLabels:
      run: smokey-server
  template:
    metadata:
      labels:
        run: smokey-server
    spec:
      containers:
      - image: gcr.io/algebraic-inn-256717/server
        name: smokey-server
